CREATE DATABASE Task3
USE Task3

CREATE TABLE Genders(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR (6) NOT NULL,
)

INSERT INTO Genders(Name) VALUES
('Woman'),
('Man')

--not executed 
CREATE TABLE Users(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(50)NOT NULL,
Surname VARCHAR(50)NOT NULL,
Username VARCHAR(255) CHECK(LEN(Username)>8) NOT NULL UNIQUE,
Password VARCHAR(255) CHECK (LEN(Password)>8)NOT NULL,
Gender INT FOREIGN KEY REFERENCES Genders(Id) NOT NULL
)




CREATE TABLE Artist (
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(50)NOT NULL,
Surname VARCHAR(50)NOT NULL,
Birthday DATE NOT NULL,
Gender INT FOREIGN KEY REFERENCES Genders(Id)
)


CREATE TABLE Categories(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(50)NOT NULL UNIQUE,
)

CREATE TABLE Music(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(50)NOT NULL UNIQUE,
Duration INT NOT NULL CHECK (Duration>0)
)

CREATE TABLE Playlist (
MusicId FOREIGN KEY REFERENCES Music(Id), 
UserId FOREIGN KEY REFERENCES  Users(Id)
)

