CREATE DATABASE Task3
USE Task3

CREATE TABLE Genders(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR (6) NOT NULL,
)

INSERT INTO Genders(Name) VALUES
('Woman'),
('Man')


CREATE TABLE Users(
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(50)NOT NULL,
Surname VARCHAR(50)NOT NULL,
Username VARCHAR(255) CHECK(LEN(Username)>8) NOT NULL UNIQUE,
Password VARCHAR(255) CHECK (LEN(Password)>8)NOT NULL,
Gender INT FOREIGN KEY REFERENCES Genders(Id) NOT NULL
)

CREATE TABLE Artist (
Id INT PRIMARY KEY IDENTITY,
Name VARCHAR(50)NOT NULL,
Surname VARCHAR(50)NOT NULL,
Birthday DATE NOT NULL,
Gender INT FOREIGN KEY REFERENCES Genders(Id)
)

